version: "3.3"
services:
  image:
    image: cm2network/steamcmd
    tty: true
    stdin_open: true
    command: "/bin/sh -c '/home/steam/steamcmd/steamcmd.sh +login anonymous +app_update 2394010 validate +quit && /home/steam/Steam/steamapps/common/PalServer/PalServer.sh ' "
    environment:
      USER_UID: "1000"
      USER_GID: "1000"
    ports:
      - "8211:8211/udp"
    volumes:
      - "./data:/home/steam/Steam/steamapps"
